name: flutter_tags
description: Flutter tags let you create clickable tags or create new ones using textField, adapting perfectly to the width of the screen.
version: 0.3.0
author: Antonino Di Natale <gyorgio88@gmail.com>
homepage: https://github.com/Dn-a/flutter_tags

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
